-- AI Trip Creator Tables
-- This migration creates tables for storing AI-generated trip itineraries

-- ============================================
-- Trips Table
-- Stores user trip itineraries generated by AI
-- ============================================
CREATE TABLE IF NOT EXISTS trips (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  origin VARCHAR(255) NOT NULL,
  origin_lat DECIMAL(10, 8),
  origin_lng DECIMAL(11, 8),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  interests TEXT[] DEFAULT '{}',
  difficulty VARCHAR(20) NOT NULL DEFAULT 'moderate' CHECK (difficulty IN ('easy', 'moderate', 'hard')),
  radius_miles INTEGER NOT NULL DEFAULT 200,
  ai_summary JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for trips
CREATE INDEX IF NOT EXISTS idx_trips_user_id ON trips(user_id);
CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trips_start_date ON trips(start_date);

-- ============================================
-- Trip Stops Table
-- Stores individual park stops within a trip
-- ============================================
CREATE TABLE IF NOT EXISTS trip_stops (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  park_id UUID REFERENCES nps_parks(id) ON DELETE SET NULL,
  park_code VARCHAR(10) NOT NULL,
  day_number INTEGER NOT NULL CHECK (day_number > 0),
  activities TEXT[] DEFAULT '{}',
  morning_plan TEXT,
  afternoon_plan TEXT,
  evening_plan TEXT,
  driving_notes TEXT,
  highlights TEXT,
  notes TEXT,
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for trip_stops
CREATE INDEX IF NOT EXISTS idx_trip_stops_trip_id ON trip_stops(trip_id);
CREATE INDEX IF NOT EXISTS idx_trip_stops_park_id ON trip_stops(park_id);
CREATE INDEX IF NOT EXISTS idx_trip_stops_day_number ON trip_stops(day_number);

-- ============================================
-- Triggers for updated_at
-- ============================================
CREATE TRIGGER update_trips_updated_at
  BEFORE UPDATE ON trips
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trip_stops_updated_at
  BEFORE UPDATE ON trip_stops
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS)
-- ============================================

-- Enable RLS on trips tables
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_stops ENABLE ROW LEVEL SECURITY;

-- Trips policies - users can only access their own trips
CREATE POLICY "Users can view their own trips"
  ON trips FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own trips"
  ON trips FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own trips"
  ON trips FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own trips"
  ON trips FOR DELETE
  USING (auth.uid() = user_id);

-- Trip stops policies - users can access stops for their own trips
CREATE POLICY "Users can view stops for their own trips"
  ON trip_stops FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM trips 
      WHERE trips.id = trip_stops.trip_id 
      AND trips.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert stops for their own trips"
  ON trip_stops FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM trips 
      WHERE trips.id = trip_stops.trip_id 
      AND trips.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update stops for their own trips"
  ON trip_stops FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM trips 
      WHERE trips.id = trip_stops.trip_id 
      AND trips.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete stops for their own trips"
  ON trip_stops FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM trips 
      WHERE trips.id = trip_stops.trip_id 
      AND trips.user_id = auth.uid()
    )
  );

-- Service role policies for admin operations
CREATE POLICY "Service role can manage trips"
  ON trips FOR ALL
  USING (auth.role() = 'service_role');

CREATE POLICY "Service role can manage trip_stops"
  ON trip_stops FOR ALL
  USING (auth.role() = 'service_role');

-- ============================================
-- Function to count user trips
-- Used for free tier enforcement
-- ============================================
CREATE OR REPLACE FUNCTION count_user_trips(p_user_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN (
    SELECT COUNT(*)::INTEGER 
    FROM trips 
    WHERE user_id = p_user_id
  );
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION count_user_trips TO authenticated;

-- ============================================
-- View for trips with park details
-- ============================================
CREATE OR REPLACE VIEW trips_with_stops AS
SELECT 
  t.id,
  t.user_id,
  t.title,
  t.origin,
  t.origin_lat,
  t.origin_lng,
  t.start_date,
  t.end_date,
  t.interests,
  t.difficulty,
  t.radius_miles,
  t.ai_summary,
  t.created_at,
  t.updated_at,
  COALESCE(
    json_agg(
      json_build_object(
        'id', ts.id,
        'day_number', ts.day_number,
        'park_code', ts.park_code,
        'park_name', np.full_name,
        'park_images', np.images,
        'activities', ts.activities,
        'morning_plan', ts.morning_plan,
        'afternoon_plan', ts.afternoon_plan,
        'evening_plan', ts.evening_plan,
        'driving_notes', ts.driving_notes,
        'highlights', ts.highlights,
        'order_index', ts.order_index
      ) ORDER BY ts.day_number, ts.order_index
    ) FILTER (WHERE ts.id IS NOT NULL),
    '[]'::json
  ) AS stops
FROM trips t
LEFT JOIN trip_stops ts ON t.id = ts.trip_id
LEFT JOIN nps_parks np ON ts.park_code = np.park_code
GROUP BY t.id;

-- Grant access to the view
GRANT SELECT ON trips_with_stops TO authenticated;